---
title: "store 101 product study"
author: "Luxiaoguang"
date: "2016年1月10日"
output: html_document
---

## 项目简介

```{r,echo=FALSE,message=FALSE,error=FALSE,warning=FALSE}
library(RMySQL)
library(dplyr)
library(rCharts)
library(lubridate)
library(ggplot2)
```

## 获取数据

```{r,echo=FALSE,cache=TRUE,results='hide'}
RTest<-dbConnect(MySQL(),user="devuser2",password="luxiaoguang",db="RTest",
                 host="dev-platform-db.czec8chdqeuo.rds.cn-north-1.amazonaws.com.cn")
allTables<-dbListTables(RTest)
length(allTables)
allTables[1:5]
dbListFields(RTest,"bnh_items")
dbGetQuery(RTest,"select count(*) from bnh_items")
itemsData<-dbReadTable(RTest,"bnh_items")
dbDisconnect(RTest)
```

```{r,echo=FALSE}
head(itemsData)
```


## 整理数据

```{r, echo=FALSE}
##remove 0 spend obs.
itemsDataclean<-filter(itemsData,itemsData$spend>0)
#remove empty data variables
itemsDataclean<-select(itemsDataclean,bask_id:original_shop_datetime)
#remove repeat variables
itemsDataclean<-itemsDataclean[,c(2,4,6,8,9,10,11)]
head(itemsDataclean)
```

## 商品分析
```{r, results = 'asis', comment = NA, message = F, echo = F}
##options(RCHART_WIDTH = 800, RCHART_HEIGHT = 500)
##length(table(itemsDataclean$prod_code))
itemdata<-itemsDataclean
itemdata$shop_datetime<-substr(itemdata$shop_datetime,1,4)

itemdatasplit<-split(itemdata,itemdata$shop_datetime)
##ym<-as.data.frame(table(customerdata$shop_datetime))
        split2013<-itemdatasplit[[1]]
        item<-group_by(split2013,prod_code)
        itemsummary2013<-summarize(item,spend=sum(spend),quantity=sum(quantity))
        itemspend2013<-arrange(itemsummary2013,desc(spend))
        toptenspend2013<-as.data.frame(itemspend2013[1:10,c(1,2)])
        itemqty2013<-arrange(itemsummary2013,desc(quantity))
        toptenqty2013<-as.data.frame(itemqty2013[1:10,c(1,3)])
        toptenspend2013$label<-"2013"
        toptenqty2013$label<-"2013"
        
        split2014<-itemdatasplit[[2]]
        item<-group_by(split2014,prod_code)
        itemsummary2014<-summarize(item,spend=sum(spend),quantity=sum(quantity))
        itemspend2014<-arrange(itemsummary2014,desc(spend))
        toptenspend2014<-as.data.frame(itemspend2014[1:10,c(1,2)])
        itemqty2014<-arrange(itemsummary2014,desc(quantity))
        toptenqty2014<-as.data.frame(itemqty2014[1:10,c(1,3)])
        toptenspend2014$label<-"2014"
        toptenqty2014$label<-"2014"
        
        split2015<-itemdatasplit[[3]]
        item<-group_by(split2015,prod_code)
        itemsummary2015<-summarize(item,spend=sum(spend),quantity=sum(quantity))
        itemspend2015<-arrange(itemsummary2015,desc(spend))
        toptenspend2015<-as.data.frame(itemspend2015[1:10,c(1,2)])
        itemqty2015<-arrange(itemsummary2015,desc(quantity))
        toptenqty2015<-as.data.frame(itemqty2015[1:10,c(1,3)])
        toptenspend2015$label<-"2015"
        toptenqty2015$label<-"2015"
        
        toptenspend<-rbind(toptenspend2013,toptenspend2014,toptenspend2015)
        toptenqty<-rbind(toptenqty2013,toptenqty2014,toptenqty2015)
        
##summary(itemsummary)
##itemspend<-arrange(itemsummary,desc(spend))
##itemqty<-arrange(itemsummary,desc(quantity))
##mainitem<-merge(itemspend[1:50,],itemqty[1:50,],all = TRUE)
p1<-qplot(prod_code,data = toptenspend,fill=label)+theme(axis.text.x=element_text(size=12,angle=45))+labs(title = "各年销售额前10名的商品")
p1
p2<-qplot(prod_code,data = toptenqty,fill=label)+theme(axis.text.x=element_text(size=12,angle=45))+labs(title = "各年销售数量前10名的商品")
p2

a<-group_by(toptenspend,prod_code)
b<-summarize(a,core=length(label))
c1<-filter(b,core=="3")
a<-group_by(toptenqty,prod_code)
b<-summarize(a,core=length(label))
c2<-filter(b,core=="3")
core<-merge(c1,c2,all = TRUE)
```

从表1中，我们可以得到，3年里，销售金额一直排名在前十位的有  
`r c1$prod_code`  
从表2中，我们可以得到，3年里，销售数量一直排名在前十位的有  
`r c2$prod_code`  
我们把表1表2合并得到8个商品作为核心商品  
`r core$prod_code`  


## 核心商品
```{r,echo=FALSE, results='hide'}
RTest<-dbConnect(MySQL(),user="devuser2",password="luxiaoguang",db="RTest",
                 host="dev-platform-db.czec8chdqeuo.rds.cn-north-1.amazonaws.com.cn")
allTables<-dbListTables(RTest)
length(allTables)
allTables[1:5]
dbListFields(RTest,"bnh_products")
dbGetQuery(RTest,"select count(*) from bnh_products")
productsData<-dbReadTable(RTest,"bnh_products")
dbDisconnect(RTest)
```

```{r,echo=FALSE}
##select topten items.
coreproduct<-merge(core,productsData,all = FALSE)
coreproduct<-coreproduct[,c(1,4,9,10,11,12,13,14,15,16,17)]
coreproduct
```

从上表我们可以得到核心商品的品名，一级目录，二级目录，三级目录等等。由于技术问题出现一些乱码。因此，分析暂停于此。

